spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://192.168.1.106:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.106
    port: 6379
  aop:
    auto: true
#server:
#  context-path: /sell
wechat:
  mpAppId: wxd46b84acdd906bc4
  mpAppSecret: 6d14b67bc3fa4a8bc31f5d393b7e6b48
  notifyUrl: http://kunkun.natapp1.cc/pay/notity




#server:
#  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
# # path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level: debug

